# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.suggestions import suggestions_pb2 as utils_dot_pb_dot_suggestions_dot_suggestions__pb2


class SuggestionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/suggestions.Suggestions/InitOrder',
                request_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.OrderInitRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.OrderInitResponse.FromString,
                )
        self.PrepareSuggestionsContext = channel.unary_unary(
                '/suggestions.Suggestions/PrepareSuggestionsContext',
                request_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventResponse.FromString,
                )
        self.GenerateSuggestions = channel.unary_unary(
                '/suggestions.Suggestions/GenerateSuggestions',
                request_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsEventResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/suggestions.Suggestions/ClearOrder',
                request_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderResponse.FromString,
                )


class SuggestionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareSuggestionsContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.OrderInitRequest.FromString,
                    response_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.OrderInitResponse.SerializeToString,
            ),
            'PrepareSuggestionsContext': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareSuggestionsContext,
                    request_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventRequest.FromString,
                    response_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventResponse.SerializeToString,
            ),
            'GenerateSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSuggestions,
                    request_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventRequest.FromString,
                    response_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsEventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderRequest.FromString,
                    response_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggestions.Suggestions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Suggestions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggestions.Suggestions/InitOrder',
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.OrderInitRequest.SerializeToString,
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.OrderInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrepareSuggestionsContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggestions.Suggestions/PrepareSuggestionsContext',
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventRequest.SerializeToString,
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggestions.Suggestions/GenerateSuggestions',
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.EventRequest.SerializeToString,
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggestions.Suggestions/ClearOrder',
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderRequest.SerializeToString,
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
