# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.fraud_detection import fraud_detection_pb2 as utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2


class FraudDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/fraud.FraudDetection/InitOrder',
                request_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderInitRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderInitResponse.FromString,
                )
        self.CheckUserFraud = channel.unary_unary(
                '/fraud.FraudDetection/CheckUserFraud',
                request_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventResponse.FromString,
                )
        self.CheckCardFraud = channel.unary_unary(
                '/fraud.FraudDetection/CheckCardFraud',
                request_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/fraud.FraudDetection/ClearOrder',
                request_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.ClearOrderRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.ClearOrderResponse.FromString,
                )


class FraudDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCardFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderInitRequest.FromString,
                    response_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderInitResponse.SerializeToString,
            ),
            'CheckUserFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserFraud,
                    request_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventRequest.FromString,
                    response_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventResponse.SerializeToString,
            ),
            'CheckCardFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCardFraud,
                    request_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventRequest.FromString,
                    response_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.ClearOrderRequest.FromString,
                    response_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.ClearOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud.FraudDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud.FraudDetection/InitOrder',
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderInitRequest.SerializeToString,
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud.FraudDetection/CheckUserFraud',
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventRequest.SerializeToString,
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckCardFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud.FraudDetection/CheckCardFraud',
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventRequest.SerializeToString,
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud.FraudDetection/ClearOrder',
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.ClearOrderRequest.SerializeToString,
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.ClearOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
