# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05\x66raud\"\'\n\x11\x46raudCheckRequest\x12\x12\n\norder_json\x18\x01 \x01(\t\"6\n\x12\x46raudCheckResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2S\n\x0e\x46raudDetection\x12\x41\n\nCheckFraud\x12\x18.fraud.FraudCheckRequest\x1a\x19.fraud.FraudCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDCHECKREQUEST']._serialized_start=32
  _globals['_FRAUDCHECKREQUEST']._serialized_end=71
  _globals['_FRAUDCHECKRESPONSE']._serialized_start=73
  _globals['_FRAUDCHECKRESPONSE']._serialized_end=127
  _globals['_FRAUDDETECTION']._serialized_start=129
  _globals['_FRAUDDETECTION']._serialized_end=212
# @@protoc_insertion_point(module_scope)
