syntax = "proto3";

package books_database;

service BooksDatabase {
    rpc Read (ReadRequest) returns (ReadResponse);
    rpc Write (WriteRequest) returns (WriteResponse);
}

message ReadRequest {
    string title = 1;
}

message ReadResponse {
    int32 stock = 1;
}

message WriteRequest {
    string title = 1;
    int32 new_stock = 2;
    int32 expected_current_stock = 3; // Used for Compare-and-Swap (concurrent writes)
    bool is_replica_update = 4; // Used internally for primary-to-backup replication
}

message WriteResponse {
    bool success = 1;
}
