# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/books_database/books_database.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/books_database/books_database.proto\x12\x0e\x62ooks_database\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"k\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\x12\x1e\n\x16\x65xpected_current_stock\x18\x03 \x01(\x05\x12\x19\n\x11is_replica_update\x18\x04 \x01(\x08\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"O\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12+\n\x05items\x18\x02 \x03(\x0b\x32\x1c.books_database.WriteRequest\" \n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"!\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\" \n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xf3\x02\n\rBooksDatabase\x12\x41\n\x04Read\x12\x1b.books_database.ReadRequest\x1a\x1c.books_database.ReadResponse\x12\x44\n\x05Write\x12\x1c.books_database.WriteRequest\x1a\x1d.books_database.WriteResponse\x12J\n\x07Prepare\x12\x1e.books_database.PrepareRequest\x1a\x1f.books_database.PrepareResponse\x12G\n\x06\x43ommit\x12\x1d.books_database.CommitRequest\x1a\x1e.books_database.CommitResponse\x12\x44\n\x05\x41\x62ort\x12\x1c.books_database.AbortRequest\x1a\x1d.books_database.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.books_database.books_database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READREQUEST']._serialized_start=64
  _globals['_READREQUEST']._serialized_end=92
  _globals['_READRESPONSE']._serialized_start=94
  _globals['_READRESPONSE']._serialized_end=123
  _globals['_WRITEREQUEST']._serialized_start=125
  _globals['_WRITEREQUEST']._serialized_end=232
  _globals['_WRITERESPONSE']._serialized_start=234
  _globals['_WRITERESPONSE']._serialized_end=266
  _globals['_PREPAREREQUEST']._serialized_start=268
  _globals['_PREPAREREQUEST']._serialized_end=347
  _globals['_PREPARERESPONSE']._serialized_start=349
  _globals['_PREPARERESPONSE']._serialized_end=381
  _globals['_COMMITREQUEST']._serialized_start=383
  _globals['_COMMITREQUEST']._serialized_end=416
  _globals['_COMMITRESPONSE']._serialized_start=418
  _globals['_COMMITRESPONSE']._serialized_end=451
  _globals['_ABORTREQUEST']._serialized_start=453
  _globals['_ABORTREQUEST']._serialized_end=485
  _globals['_ABORTRESPONSE']._serialized_start=487
  _globals['_ABORTRESPONSE']._serialized_end=519
  _globals['_BOOKSDATABASE']._serialized_start=522
  _globals['_BOOKSDATABASE']._serialized_end=893
# @@protoc_insertion_point(module_scope)
