syntax = "proto3";

package books_database;

service BooksDatabase {
    rpc Read (ReadRequest) returns (ReadResponse);
    rpc Write (WriteRequest) returns (WriteResponse);
    
    // 2PC operations
    rpc Prepare (PrepareRequest) returns (PrepareResponse);
    rpc Commit (CommitRequest) returns (CommitResponse);
    rpc Abort (AbortRequest) returns (AbortResponse);
}

message ReadRequest {
    string title = 1;
}

message ReadResponse {
    int32 stock = 1;
}

message WriteRequest {
    string title = 1;
    int32 new_stock = 2;
    int32 expected_current_stock = 3; // Used for Compare-and-Swap (concurrent writes)
    bool is_replica_update = 4; // Used internally for primary-to-backup replication
}

message WriteResponse {
    bool success = 1;
}

// 2PC Messages
message PrepareRequest {
    string order_id = 1;
    repeated WriteRequest items = 2; // The items to update for this order
}

message PrepareResponse {
    bool ready = 1;
}

message CommitRequest {
    string order_id = 1;
}

message CommitResponse {
    bool success = 1;
}

message AbortRequest {
    string order_id = 1;
}

message AbortResponse {
    bool aborted = 1;
}
