syntax = "proto3";

package order_queue;

service OrderQueue {
    rpc Enqueue (EnqueueRequest) returns (EnqueueResponse);
    rpc Dequeue (DequeueRequest) returns (DequeueResponse);
    rpc GetQueueStatus (QueueStatusRequest) returns (QueueStatusResponse);
}

message EnqueueRequest {
    string order_id = 1;
    string order_json = 2;
}

message EnqueueResponse {
    bool success = 1;
    string reason = 2;
    int32 queue_size = 3;
}

message DequeueRequest {
    string executor_id = 1;
}

message DequeueResponse {
    bool success = 1;
    string reason = 2;
    bool has_order = 3;
    string order_id = 4;
    string order_json = 5;
    int32 queue_size = 6;
}

message QueueStatusRequest {}

message QueueStatusResponse {
    int32 queue_size = 1;
}