# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\x0border_queue\"6\n\x0e\x45nqueueRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_json\x18\x02 \x01(\t\"F\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12\n\nqueue_size\x18\x03 \x01(\x05\"%\n\x0e\x44\x65queueRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\"\x7f\n\x0f\x44\x65queueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x11\n\thas_order\x18\x03 \x01(\x08\x12\x10\n\x08order_id\x18\x04 \x01(\t\x12\x12\n\norder_json\x18\x05 \x01(\t\x12\x12\n\nqueue_size\x18\x06 \x01(\x05\"\x14\n\x12QueueStatusRequest\")\n\x13QueueStatusResponse\x12\x12\n\nqueue_size\x18\x01 \x01(\x05\x32\xed\x01\n\nOrderQueue\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponse\x12S\n\x0eGetQueueStatus\x12\x1f.order_queue.QueueStatusRequest\x1a .order_queue.QueueStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENQUEUEREQUEST']._serialized_start=55
  _globals['_ENQUEUEREQUEST']._serialized_end=109
  _globals['_ENQUEUERESPONSE']._serialized_start=111
  _globals['_ENQUEUERESPONSE']._serialized_end=181
  _globals['_DEQUEUEREQUEST']._serialized_start=183
  _globals['_DEQUEUEREQUEST']._serialized_end=220
  _globals['_DEQUEUERESPONSE']._serialized_start=222
  _globals['_DEQUEUERESPONSE']._serialized_end=349
  _globals['_QUEUESTATUSREQUEST']._serialized_start=351
  _globals['_QUEUESTATUSREQUEST']._serialized_end=371
  _globals['_QUEUESTATUSRESPONSE']._serialized_start=373
  _globals['_QUEUESTATUSRESPONSE']._serialized_end=414
  _globals['_ORDERQUEUE']._serialized_start=417
  _globals['_ORDERQUEUE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
