# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\"4\n\x1eTransactionVerificationRequest\x12\x12\n\norder_json\x18\x01 \x01(\t\"C\n\x1fTransactionVerificationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\x89\x01\n\x17TransactionVerification\x12n\n\x11VerifyTransaction\x12+.transaction.TransactionVerificationRequest\x1a,.transaction.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_start=47
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_end=99
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=101
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=168
  _globals['_TRANSACTIONVERIFICATION']._serialized_start=171
  _globals['_TRANSACTIONVERIFICATION']._serialized_end=308
# @@protoc_insertion_point(module_scope)
