syntax = "proto3";

package transaction;

service TransactionVerification {
    rpc InitOrder (OrderInitRequest) returns (OrderInitResponse);
    rpc ValidateItems (EventRequest) returns (EventResponse);
    rpc CheckStock (EventRequest) returns (EventResponse);
    rpc ValidateUserData (EventRequest) returns (EventResponse);
    rpc ValidateCardFormat (EventRequest) returns (EventResponse);
    rpc ClearOrder (ClearOrderRequest) returns (ClearOrderResponse);
}

message VectorClock {
    int32 transaction_verification = 1;
    int32 fraud_detection = 2;
    int32 suggestions = 3;
}

message OrderInitRequest {
    string order_id = 1;
    string order_json = 2;
    VectorClock vector_clock = 3;
}

message OrderInitResponse {
    bool success = 1;
    string reason = 2;
    VectorClock vector_clock = 3;
}

message EventRequest {
    string order_id = 1;
    VectorClock vector_clock = 2;
}

message EventResponse {
    bool success = 1;
    string reason = 2;
    string event_name = 3;
    VectorClock vector_clock = 4;
}

message ClearOrderRequest {
    string order_id = 1;
    VectorClock final_vector_clock = 2;
}

message ClearOrderResponse {
    bool success = 1;
    string reason = 2;
    VectorClock vector_clock = 3;
}
