# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.order_executor import order_executor_pb2 as utils_dot_pb_dot_order__executor_dot_order__executor__pb2


class OrderExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/order_executor.OrderExecutor/Ping',
                request_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.PingRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.PingResponse.FromString,
                )
        self.Election = channel.unary_unary(
                '/order_executor.OrderExecutor/Election',
                request_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ElectionRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ElectionResponse.FromString,
                )
        self.AnnounceLeader = channel.unary_unary(
                '/order_executor.OrderExecutor/AnnounceLeader',
                request_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.CoordinatorRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.CoordinatorResponse.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/order_executor.OrderExecutor/GetStatus',
                request_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.StatusRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.StatusResponse.FromString,
                )


class OrderExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.PingRequest.FromString,
                    response_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.PingResponse.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ElectionRequest.FromString,
                    response_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ElectionResponse.SerializeToString,
            ),
            'AnnounceLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceLeader,
                    request_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.CoordinatorRequest.FromString,
                    response_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.CoordinatorResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.StatusRequest.FromString,
                    response_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_executor.OrderExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderExecutor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_executor.OrderExecutor/Ping',
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.PingRequest.SerializeToString,
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_executor.OrderExecutor/Election',
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ElectionRequest.SerializeToString,
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ElectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnnounceLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_executor.OrderExecutor/AnnounceLeader',
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.CoordinatorRequest.SerializeToString,
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.CoordinatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_executor.OrderExecutor/GetStatus',
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.StatusRequest.SerializeToString,
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
