# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_executor/order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/order_executor/order_executor.proto\x12\x0eorder_executor\"\'\n\x0bPingRequest\x12\x18\n\x10\x66rom_executor_id\x18\x01 \x01(\x05\"E\n\x0cPingResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x13\n\x0b\x65xecutor_id\x18\x02 \x01(\x05\x12\x11\n\tleader_id\x18\x03 \x01(\x05\"\'\n\x0f\x45lectionRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\"G\n\x10\x45lectionResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x14\n\x0cresponder_id\x18\x02 \x01(\x05\x12\x0e\n\x06reason\x18\x03 \x01(\t\"\'\n\x12\x43oordinatorRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"@\n\x13\x43oordinatorResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x13\n\x0b\x65xecutor_id\x18\x02 \x01(\x05\"\x0f\n\rStatusRequest\"\x83\x01\n\x0eStatusResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x11\n\tis_leader\x18\x03 \x01(\x08\x12\x1c\n\x14\x65lection_in_progress\x18\x04 \x01(\x08\x12\x18\n\x10known_peer_count\x18\x05 \x01(\x05\x32\xc8\x02\n\rOrderExecutor\x12\x41\n\x04Ping\x12\x1b.order_executor.PingRequest\x1a\x1c.order_executor.PingResponse\x12M\n\x08\x45lection\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12Y\n\x0e\x41nnounceLeader\x12\".order_executor.CoordinatorRequest\x1a#.order_executor.CoordinatorResponse\x12J\n\tGetStatus\x12\x1d.order_executor.StatusRequest\x1a\x1e.order_executor.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_executor.order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGREQUEST']._serialized_start=64
  _globals['_PINGREQUEST']._serialized_end=103
  _globals['_PINGRESPONSE']._serialized_start=105
  _globals['_PINGRESPONSE']._serialized_end=174
  _globals['_ELECTIONREQUEST']._serialized_start=176
  _globals['_ELECTIONREQUEST']._serialized_end=215
  _globals['_ELECTIONRESPONSE']._serialized_start=217
  _globals['_ELECTIONRESPONSE']._serialized_end=288
  _globals['_COORDINATORREQUEST']._serialized_start=290
  _globals['_COORDINATORREQUEST']._serialized_end=329
  _globals['_COORDINATORRESPONSE']._serialized_start=331
  _globals['_COORDINATORRESPONSE']._serialized_end=395
  _globals['_STATUSREQUEST']._serialized_start=397
  _globals['_STATUSREQUEST']._serialized_end=412
  _globals['_STATUSRESPONSE']._serialized_start=415
  _globals['_STATUSRESPONSE']._serialized_end=546
  _globals['_ORDEREXECUTOR']._serialized_start=549
  _globals['_ORDEREXECUTOR']._serialized_end=877
# @@protoc_insertion_point(module_scope)
